---
- name: Update repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install build deps
  ansible.builtin.apt:
    pkg:
      - crun
      - git
      - golang-1.21-go
      - go-md2man
      - iptables
      - libassuan-dev
      - libc6-dev
      - libdevmapper-dev
      - libglib2.0-dev
      - libgpgme-dev
      - libgpg-error-dev
      - libprotobuf-dev
      - libprotobuf-c-dev
      - libsystemd-dev
      - pkg-config
      - containernetworking-plugins
      - conmon
      - uidmap
      - make

- name: Make source dir
  ansible.builtin.file:
    path: "{{ podman_build_dir }}"/src
    state: directory
    mode: 0755
    owner: "{{ podman_build_user }}"

- name: Make target dir
  ansible.builtin.file:
    path: "{{ podman_build_dir }}"/target
    state: directory
    mode: 0755
    owner: "{{ podman_build_user }}"

- name: Download podman source code
  ansible.builtin.git:
    repo: 'https://github.com/containers/podman.git'
    version: 'v{{ podman_source_version }}'
    dest: "{{ podman_build_dir }}"/src/podman
    depth: 1

- name: Run make
  community.general.make:
    chdir: "{{ podman_build_dir }}"/src/podman
    params:
      BUILDTAGS: "systemd exclude_graphdriver_btrfs"
      PREFIX: "{{ podman_install_prefix }}"
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/go-1.21/bin"

- name: Run make install
  community.general.make:
    chdir: "{{ podman_build_dir }}"/src/podman
    target: install
    params:
      PREFIX: "{{ podman_build_dir }}"/target
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/go-1.21/bin"

- name: Prepare archive
  community.general.archive:
    path: "{{ podman_build_dir }}"/target
    dest: "{{ podman_build_dir }}/target/podman-{{ podman_version }}-{{ ansible_distribution }}{{ ansible_distribution_version }}.tgz"

- name: Fetch archive
  ansible.builtin.fetch:
    src: "/target/podman-{{ podman_version }}-{{ ansible_distribution }}{{ ansible_distribution_version }}.tgz"
    dest: archives/
    flat: yes
