---
- name: Update repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install build deps
  ansible.builtin.apt:
    pkg:
      - crun
      - git
      - golang-1.21-go
      - go-md2man
      - iptables
      - libassuan-dev
      - libc6-dev
      - libdevmapper-dev
      - libglib2.0-dev
      - libgpgme-dev
      - libgpg-error-dev
      - libprotobuf-dev
      - libprotobuf-c-dev
      - libsystemd-dev
      - pkg-config
      - containernetworking-plugins
      - conmon
      - uidmap
      - make

- name: Set dir paths
  ansible.builtin.set_fact:
    source_dir: "{{ podman_build_dir }}"/src
    package_version: "{{ podman_version }}{{ '-' + podman_build_rev if podman_build_rev != '' else '' }}"
    target_dir: "{{ podman_build_dir }}/podman_{{ package_version }}"

- name: Make source dir
  ansible.builtin.file:
    path: "{{ source_dir }}"
    state: directory
    mode: 0755
    owner: "{{ podman_build_user }}"

- name: Make target dir
  ansible.builtin.file:
    path: "{{ target_dir }}"
    state: directory
    mode: 0755
    owner: "{{ podman_build_user }}"

- name: Download podman source code
  ansible.builtin.git:
    repo: 'https://github.com/containers/podman.git'
    version: 'v{{ podman_source_version }}'
    dest: "{{ source_dir }}"/podman
    depth: 1

- name: Run make
  community.general.make:
    chdir: "{{ source_dir }}"/podman
    params:
      BUILDTAGS: "systemd exclude_graphdriver_btrfs"
      PREFIX: "{{ podman_install_prefix }}"
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/go-1.21/bin"

- name: Run make install
  community.general.make:
    chdir: "{{ podman_build_dir }}"/src/podman
    target: install
    params:
      PREFIX: "{{ target_dir }}"
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/go-1.21/bin"

- name: Create control file
  ansible.builtin.template:
    src: templates/control.j2
    dest: "{{ target_dir }}"/DEBIAN/control
    mode : 0644

- name: Build the package
  ansible.builtin.command:
    argv:
      - dpkg-deb
      - --build
      - "podman-{{ package_version }}"
    chdir: "{{ podman_build_dir }}"

- name: Fetch package
  ansible.builtin.fetch:
    src: "{{ podman_build_dir }}/podman-{{ package_version }}.deb"
    dest: packages/
    flat: yes
