---
- name: Ensure configuration directory is present
  ansible.builtin.file:
    path: /etc/containers
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install containers.conf
  ansible.builtin.template:
    src: templates/containers.conf.j2
    dest: /etc/containers/containers.conf
    mode: 0644
    owner: root
    group: root

- name: Install storage.conf
  ansible.builtin.template:
    src: templates/storage.conf.j2
    dest: /etc/containers/storage.conf
    mode: 0644
    owner: root
    group: root

- name: Install registries.conf
  ansible.builtin.template:
    src: templates/registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0644
    owner: root
    group: root

- name: Install policy.json
  ansible.builtin.copy:
    src: files/policy.json
    dest: /etc/containers/policy.json
    owner: root
    group: root
    mode: 0644
