---
- name: Install
  ansible.builtin.include_tasks: install.yml
  when: podman_do_install

- name: Configure
  ansible.builtin.include_tasks: configure.yml

- name: Setup nvidia gpus
  ansible.builtin.include_tasks: nvidia.yml
  when: podman_setup_nvidia
