name: Build .deb for release
on:
  push:
    branches:
      - 'build'

jobs:
    build:
      runs-on: ubuntu-22.04
      permissions:
        # to be allowed to create releases
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Make output dir
          run: mkdir output

        - name: Run builds
          run: sh build.sh

        - name: Upload netavark package
          uses: svenstaro/upload-release-action@v2
          with:
            file: output/netavark-*.deb
            file_glob: true
            tag: ${{ github.ref }}

        - name: Upload podman package
          uses: svenstaro/upload-release-action@v2
          with:
            file: output/podman-*.deb
            file_glob: true
            tag: ${{ github.ref }}
            
