name: Build .deb for release
on:
  push:
    branches:
      - 'build'

jobs:
    build:
      runs-on: ubuntu-22.04
      permissions:
        # to be allowed to crrate releases
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Make output dir
          run: mkdir output

        - name: Run 22.04 dockerfile
          run: docker build -t podman-build -f Dockerfile.22.04 .

        - name: Extract .deb
          run: docker run --rm --mount type=bind,src=$(pwd)/output,dst=/output podman-build bash -c "cp /tmp/podman-*.deb /tmp/netavark-*.deb /output"

        - name: Run 24.04 dockerfile
          run: docker build -t podman-build -f Dockerfile.24.04 .

        - name: Extract .deb
          run: docker run --rm --mount type=bind,src=$(pwd)/output,dst=/output podman-build bash -c "cp /tmp/podman-*.deb /tmp/netavark-*.deb /output"

        - name: Upload netavark package
          uses: svenstaro/upload-release-action@v2
          with:
            file: output/netavark-*.deb
            file_glob: true
            tag: ${{ github.ref }}

        - name: Upload podman package
          uses: svenstaro/upload-release-action@v2
          with:
            file: output/podman-*.deb
            file_glob: true
            tag: ${{ github.ref }}
            
